// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgDfEOHfnDTb05uCGIxz5NZNkXrQF3EC0',
    appId: '1:941839892238:web:e2223f31ced644dbac215f',
    messagingSenderId: '941839892238',
    projectId: 'football-mojo',
    authDomain: 'football-mojo.firebaseapp.com',
    databaseURL: 'https://football-mojo.firebaseio.com',
    storageBucket: 'football-mojo.appspot.com',
    measurementId: 'G-032VGMPJFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvqa03yfFA8iiMuUdfvYUAiqPeLG4O_ek',
    appId: '1:941839892238:android:d0657eb268d58fe8ac215f',
    messagingSenderId: '941839892238',
    projectId: 'football-mojo',
    databaseURL: 'https://football-mojo.firebaseio.com',
    storageBucket: 'football-mojo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBXhkDS-GNAlWc6qxvXLl8Z5SJ8mGyhCc',
    appId: '1:941839892238:ios:375716fa125e25cfac215f',
    messagingSenderId: '941839892238',
    projectId: 'football-mojo',
    databaseURL: 'https://football-mojo.firebaseio.com',
    storageBucket: 'football-mojo.appspot.com',
    androidClientId: '941839892238-4kjeusgddi8jd3euohqngn9quts111bh.apps.googleusercontent.com',
    iosClientId: '941839892238-l1ftlv1b469eav988rndfqlqkfsfthka.apps.googleusercontent.com',
    iosBundleId: 'com.example.sportsmojo',
  );
}
