import type { Metadata, Viewport } from 'next';
import { Inter, Sora } from 'next/font/google';
import './globals.css';
import { Analytics } from '@vercel/analytics/next';
import { SITE } from '@/lib/site';
import { SiteHeader, SiteFooter } from '@/components/site-chrome';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter', display: 'swap' });
const sora = Sora({ subsets: ['latin'], weight: ['600', '700', '800'], variable: '--font-sora', display: 'swap' });

export const metadata: Metadata = {
  metadataBase: new URL(SITE.url),
  title: {
    default: `${SITE.name} — World Cup 2026 Football App, Brackets, Fantasy & Live Scores`,
    template: `%s · ${SITE.name}`,
  },
  description: SITE.description,
  keywords: [...SITE.keywords],
  applicationName: SITE.name,
  authors: [{ name: SITE.name }],
  creator: SITE.name,
  publisher: SITE.name,
  category: 'sports',
  alternates: { canonical: '/' },
  manifest: '/manifest.webmanifest',
  icons: {
    icon: [{ url: '/logo.png', type: 'image/png' }],
    apple: '/logo.png',
  },
  openGraph: {
    type: 'website',
    siteName: SITE.name,
    url: SITE.url,
    title: `${SITE.name} — Your World Cup 2026 Football Companion`,
    description: SITE.description,
    locale: 'en_US',
    // Image is generated by app/opengraph-image.tsx (Next injects it).
  },
  twitter: {
    card: 'summary_large_image',
    title: `${SITE.name} — World Cup 2026 Football App`,
    description: SITE.description,
    // Twitter falls back to the generated opengraph-image too.
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, 'max-image-preview': 'large', 'max-snippet': -1 },
  },
};

export const viewport: Viewport = {
  themeColor: '#0E0D0B',
  colorScheme: 'dark',
};

// Rich structured data — helps Google show the app card + sitelinks.
const jsonLd = {
  '@context': 'https://schema.org',
  '@graph': [
    {
      '@type': 'Organization',
      '@id': `${SITE.url}/#org`,
      name: SITE.name,
      url: SITE.url,
      logo: `${SITE.url}/logo.png`,
    },
    {
      '@type': 'WebSite',
      '@id': `${SITE.url}/#website`,
      url: SITE.url,
      name: SITE.name,
      description: SITE.description,
      publisher: { '@id': `${SITE.url}/#org` },
      inLanguage: 'en',
    },
    {
      '@type': 'MobileApplication',
      '@id': `${SITE.url}/#app`,
      name: SITE.name,
      operatingSystem: 'ANDROID',
      applicationCategory: 'SportsApplication',
      url: SITE.url,
      downloadUrl: SITE.playStoreUrl,
      installUrl: SITE.playStoreUrl,
      description: SITE.description,
      offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
      publisher: { '@id': `${SITE.url}/#org` },
    },
  ],
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${inter.variable} ${sora.variable}`}>
      <body className="font-sans">
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
        <SiteHeader />
        <main>{children}</main>
        <SiteFooter />
        <Analytics />
      </body>
    </html>
  );
}
